name: velocore
description: Reusable ad hocs
version: 0.0.1
homepage: https://github.com/Pomis/velocore

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

