name: velocore
description: Reusable ad hocs
version: 0.0.2
homepage: https://github.com/Pomis/velocore

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

